---
# tasks file for helm-cli

- name: check if helm-v{{ helm_cli_version }}-linux-amd64.tar.gz file exists
  stat: 
    path: /vagrant/cache/files/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz
  register: result

- name: create /vagrant/cache/images, if it doesn't exist
  file:
    path: /vagrant/cache/files
    state: directory

- name: cache Helm {{ helm_cli_version }} CLI archive
  shell:
    # accessing the vagrant share is a bit different between host operating systems requiring this backflip
    tempfile=$(mktemp -d /tmp/nemonik.XXXXXXXXXX)

    trap "{ rm -Rf $tempfile; }" EXIT

    if [[ "windows" == "{{ host_os }}" ]]; then
      sudo su;
    fi

    curl https://get.helm.sh/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz -o ${tempfile}/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz

    cp -f ${tempfile}/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz /vagrant/cache/files/.

    echo "{{ helm_cli_checksum }} /vagrant/cache/files/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz" | sha256sum -c
  args:
    executable: /bin/bash
  when: result.stat.exists != true

- name: unarchive Helm {{ helm_cli_version }} CLI into /usr/local/bin
  become: yes
  shell:
    tempfile=$(mktemp -d /tmp/nemonik.XXXXXXXXXX)

    trap "{ rm -Rf $tempfile; }" EXIT

    cp /vagrant/cache/files/helm-v{{ helm_cli_version }}-linux-amd64.tar.gz ${tempfile}

    cd ${tempfile}

    tar -zxvf helm-v{{ helm_cli_version }}-linux-amd64.tar.gz
   
    cp -f linux-amd64/helm /usr/local/bin

    chmod 0755 /usr/local/bin/helm
  args:
    executable: /bin/bash
